name: BlockBreakSpeed
version: '${project.version}'
main: me.walcriz.blockbreakspeed.Main
api-version: 1.19
authors: [Walcriz]
website: walcriz.net

softdepend: [ ProtocolLib ]

commands:
  bbsreload:
    permission: blockbreakspeed.config.reload
